### ISSUE TITLE
Connectivity issues using Kukai Mobile on https://staging.envited-x.net/

### ISSUE THREAD

**Issue by dansan566** [kukai-wallet/kukai-mobile-ios#14]
Network: Ghostnet
Version: v.1.1.1 (350)
Device: iPhone12

Steps to reproduce:
1. Imported an account into Kukai Mobile Wallet
2. Switched the network to "Ghostnet"
3. I want to connect Kukai Mobile Wallet using "WalletConnect" within Beacon 
4. I scanned the QR Code
5. I connected with dApp (https://staging.envited-x.net/) 
6. I wanted to mint an NFT

So far, only once I saw the operation screen. Clearing the local storage in dev tools also has no impact - it only resets the Kukai Mobile connection (see 3.). 

What I would expect: 
The operation screen always pops up like this:
![image](https://github.com/user-attachments/assets/2d167dc9-7ea0-40ee-9a1e-349df57e5b3b)

**Comment by simonmcl** [comment]
@dansan566 Hi Daniel, I'm trying to test this with my own app to debug it but I can't get into the dApp. The first QR code returns a URL: `openid-vc://` which isn't supported by kukai and the "register here" link is not bringing me to a new screen. How can I get registered to test it?

If you are developing this site, please note: the QRCode on this screen doesn't have the ability to copy/paste the value. This is essential for users to be able to use a mobile browser and a mobile wallet on the same device, as you can't scan a QRCode on the phone you are using. Most wallets provide the ability to paste the contents of a QRCode instead of scanning to help work around this issue

**Comment by dansan566** [comment]
@simonmcl thanks for your reply! Yes, presenting a verified credential is not supported by Kukai. We are using Altme to handle verified credentials. However, once you the user is logged-in, he still needs to connect this wallet to mint. I doubt that users will use two separate wallets (Altme for presenting the VC, Kukai to mint) - however, I wanted to try the Kukai Mobile App and then found the issue. It is possible to mint the asset with Altme but also with Temple. How can we proceed without onboarding you (=getting the VC) but making you aware of the issue? It seems to be stuck here:

![Bildschirmfoto 2024-12-05 um 14 32 27](https://github.com/user-attachments/assets/c5993ff0-1d12-4690-b2db-833f4d58e7b4)

Regarding the QRCode: We don't support that (yet)

**Comment by dansan566** [comment]
Just tried it again and now it's working. It is really hard to reproduce...

**Comment by simonmcl** [comment]
@dansan566 

> Preparing Request for ... wallet

This is a Beacon issue. If it was a wallet issue it would say this:

![Screenshot 2024-12-05 at 14 20 22](https://github.com/user-attachments/assets/932b0f97-8e2d-4e61-9c48-207a0568c4ec)

"preparing" means it hasn't sent anything to the wallet yet. There has been a large uptick in users reporting issues with Beacon lately. Some users reporting that it can take longer than 30 seconds to get passed this prompt before the wallet receives anything. I've doubled checked https://ghostnet.objkt.com/ and everything seems to be working fine with kukai. This is a Beacon issue, you will need to reach out to them for support
